application: bhatia-io
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /blog/files
  static_dir: blog/static/files
- url: /.*
  script: tushar.settings.application
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
